import { generateKeyPairSync } from 'node:crypto';
import { spawn, type ChildProcess } from 'node:child_process';
import { createServer } from 'node:net';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  openSync,
  readFileSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { request } from 'node:https';
import { ENVTEST_K8S_VERSION } from './version.js';

export interface EnvtestServer {
  /** HTTPS URL of the kube-apiserver, e.g. https://127.0.0.1:64430 */
  readonly server: string;
  /** Bearer token for the system:masters admin user. */
  readonly token: string;
  /** Stop the apiserver and etcd and remove the temp dir. Idempotent. */
  stop(): void;
}

const ADMIN_TOKEN = 'p9r-envtest-admin-token';

function assetsDir(): string {
  const fromEnv = process.env.KUBEBUILDER_ASSETS;
  if (fromEnv !== undefined && fromEnv.length > 0) {
    return fromEnv;
  }
  // Fall back to the default setup-envtest cache location.
  const home = process.env.HOME ?? '';
  const arch = process.arch === 'x64' ? 'amd64' : process.arch;
  return join(
    home,
    '.local/share/kubebuilder-envtest/k8s',
    `${ENVTEST_K8S_VERSION}-${process.platform}-${arch}`,
  );
}

function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const srv = createServer();
    srv.unref();
    srv.on('error', reject);
    srv.listen(0, '127.0.0.1', () => {
      const addr = srv.address();
      if (addr === null || typeof addr === 'string') {
        reject(new Error('could not determine free port'));
        return;
      }
      const { port } = addr;
      srv.close(() => {
        resolve(port);
      });
    });
  });
}

function healthz(server: string, token: string): Promise<boolean> {
  return new Promise((resolve) => {
    const req = request(
      `${server}/healthz`,
      {
        method: 'GET',
        rejectUnauthorized: false,
        headers: { Authorization: `Bearer ${token}` },
      },
      (res) => {
        res.resume();
        resolve(res.statusCode === 200);
      },
    );
    req.on('error', () => {
      resolve(false);
    });
    req.end();
  });
}

async function waitForHealthy(
  server: string,
  token: string,
  attempts: number,
): Promise<void> {
  for (let i = 0; i < attempts; i++) {
    if (await healthz(server, token)) {
      return;
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error(
    `apiserver did not become healthy after ${String(attempts)} attempts`,
  );
}

/**
 * Boot a real etcd + kube-apiserver (no kubelet, no controllers) following the
 * controller-runtime envtest recipe: token-auth admin, AlwaysAllow authz, a
 * self-signed serving cert generated by the apiserver, and an in-memory RSA
 * service-account keypair. Returns connection info and a teardown.
 */
export async function startEnvtest(): Promise<EnvtestServer> {
  const assets = assetsDir();
  const dir = mkdtempSync(join(tmpdir(), 'p9r-envtest-'));

  const { publicKey, privateKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs1', format: 'pem' },
  });
  const saPub = join(dir, 'sa.pub');
  const saKey = join(dir, 'sa.key');
  const tokenFile = join(dir, 'token.csv');
  writeFileSync(saPub, publicKey);
  writeFileSync(saKey, privateKey);
  writeFileSync(tokenFile, `${ADMIN_TOKEN},admin,admin,system:masters\n`);

  const etcdPort = await freePort();
  const etcdPeerPort = await freePort();
  const apiPort = await freePort();
  const etcdUrl = `http://127.0.0.1:${String(etcdPort)}`;
  const server = `https://127.0.0.1:${String(apiPort)}`;

  const children: ChildProcess[] = [];
  let stopped = false;
  const stop = (): void => {
    if (stopped) {
      return;
    }
    stopped = true;
    for (const child of children) {
      child.kill('SIGKILL');
    }
    rmSync(dir, { recursive: true, force: true });
  };

  const etcdLog = join(dir, 'etcd.log');
  const apiLog = join(dir, 'api.log');
  const etcdFd = openSync(etcdLog, 'w');
  const apiFd = openSync(apiLog, 'w');

  const etcd = spawn(
    join(assets, 'etcd'),
    [
      '--data-dir',
      join(dir, 'etcd'),
      '--listen-client-urls',
      etcdUrl,
      '--advertise-client-urls',
      etcdUrl,
      '--listen-peer-urls',
      `http://127.0.0.1:${String(etcdPeerPort)}`,
    ],
    { stdio: ['ignore', etcdFd, etcdFd] },
  );
  children.push(etcd);

  const api = spawn(
    join(assets, 'kube-apiserver'),
    [
      '--etcd-servers',
      etcdUrl,
      '--secure-port',
      String(apiPort),
      '--cert-dir',
      join(dir, 'certs'),
      '--service-account-issuer',
      'https://kubernetes.default.svc',
      '--service-account-key-file',
      saPub,
      '--service-account-signing-key-file',
      saKey,
      '--service-cluster-ip-range',
      '10.0.0.0/24',
      '--disable-admission-plugins',
      'ServiceAccount',
      '--authorization-mode',
      'AlwaysAllow',
      '--token-auth-file',
      tokenFile,
      // Boolean flags must use the `=` form or Go treats the value as a
      // positional argument.
      '--anonymous-auth=true',
    ],
    { stdio: ['ignore', apiFd, apiFd] },
  );
  children.push(api);

  try {
    await waitForHealthy(server, ADMIN_TOKEN, 120);
  } catch (error) {
    const tail = (path: string): string =>
      existsSync(path)
        ? readFileSync(path, 'utf8').split('\n').slice(-15).join('\n')
        : '(no log)';
    const apiTail = tail(apiLog);
    const etcdTail = tail(etcdLog);
    stop();
    throw new Error(
      `${String(error)}\n--- kube-apiserver ---\n${apiTail}\n--- etcd ---\n${etcdTail}`,
    );
  }

  return { server, token: ADMIN_TOKEN, stop };
}
