#!/usr/bin/env bun
/**
 * Target-aware single-binary build.
 *
 * The compiled binary embeds onnxruntime's native shared library and
 * extracts it next to the .node binding at startup (the binding resolves it
 * from its own directory). Each platform needs a different library file, so
 * this script generates a small entry wrapper per target with the right
 * `with { type: 'file' }` import, then runs `bun build --compile`.
 *
 *   bun scripts/build.ts                # host platform → dist/p9r
 *   bun scripts/build.ts linux-x64      # cross-compile → dist/p9r-linux-x64
 *   bun scripts/build.ts all            # every supported target
 */
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';

interface Target {
  /** bun build --target value. */
  bunTarget: string;
  /** Path under onnxruntime-node/bin/napi-v6/ to the shared library. */
  libSource: string;
  /** Canonical file name the binding's loader looks for. */
  libName: string;
  /** Release artifact suffix. */
  suffix: string;
}

const TARGETS: Record<string, Target> = {
  'darwin-arm64': {
    bunTarget: 'bun-darwin-arm64',
    libSource: 'darwin/arm64/libonnxruntime.1.24.3.dylib',
    libName: 'libonnxruntime.1.24.3.dylib',
    suffix: 'darwin-arm64',
  },
  'linux-x64': {
    bunTarget: 'bun-linux-x64',
    libSource: 'linux/x64/libonnxruntime.so.1',
    libName: 'libonnxruntime.so.1',
    suffix: 'linux-x64',
  },
  'linux-arm64': {
    bunTarget: 'bun-linux-arm64',
    libSource: 'linux/arm64/libonnxruntime.so.1',
    libName: 'libonnxruntime.so.1',
    suffix: 'linux-arm64',
  },
  'windows-x64': {
    bunTarget: 'bun-windows-x64',
    libSource: 'win32/x64/onnxruntime.dll',
    libName: 'onnxruntime.dll',
    suffix: 'windows-x64',
  },
};

function hostKey(): string {
  const os = process.platform === 'win32' ? 'windows' : process.platform;
  return `${os}-${process.arch}`;
}

function entrySource(target: Target): string {
  return `#!/usr/bin/env bun
// GENERATED by scripts/build.ts — do not edit, do not commit.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import ortLibPath from '../node_modules/onnxruntime-node/bin/napi-v6/${target.libSource}' with { type: 'file' };

// Bun embeds assets under content-hashed names; the onnxruntime .node
// binding Bun extracts to the temp dir resolves its shared library from
// that same directory, so it must exist there under its canonical name.
if (ortLibPath.includes('$bunfs') || ortLibPath.includes('~BUN')) {
  const dest = join(tmpdir(), '${target.libName}');
  if (!existsSync(dest)) {
    writeFileSync(dest, readFileSync(ortLibPath));
  }
}

const { main } = await import('../src/main.js');

main(process.argv.slice(2));
`;
}

function build(key: string, target: Target): boolean {
  const libPath = join(
    'node_modules/onnxruntime-node/bin/napi-v6',
    target.libSource,
  );
  if (!existsSync(libPath)) {
    console.error(`✗ ${key}: missing native library ${libPath}`);
    return false;
  }
  const entryPath = `bin/p9r-entry.${key}.generated.ts`;
  writeFileSync(entryPath, entrySource(target));
  const isHost = key === hostKey();
  const outfile = isHost ? 'dist/p9r' : `dist/p9r-${target.suffix}`;
  mkdirSync('dist', { recursive: true });
  try {
    const proc = spawnSync(
      'bun',
      [
        'build',
        '--compile',
        `--target=${target.bunTarget}`,
        entryPath,
        '--outfile',
        outfile,
      ],
      { stdio: 'inherit' },
    );
    if (proc.status !== 0) {
      console.error(`✗ ${key}: bun build exited ${String(proc.status)}`);
      return false;
    }
    console.log(`✓ ${key} → ${outfile}`);
    return true;
  } finally {
    rmSync(entryPath, { force: true });
  }
}

const arg = process.argv[2] ?? hostKey();
const keys = arg === 'all' ? Object.keys(TARGETS) : [arg];
let ok = true;
for (const key of keys) {
  const target = TARGETS[key];
  if (target === undefined) {
    console.error(
      `unknown target "${key}" — known: ${Object.keys(TARGETS).join(', ')}, all`,
    );
    process.exit(1);
  }
  ok = build(key, target) && ok;
}
process.exit(ok ? 0 : 1);
